create table pokemon(
    id integer generated by DEFAULT as identity primary key,
    num text not null unique,
    name text not null,
    pre_evolution json,
    next_evolution json
);
create table pokemon_type(
    id integer generated by DEFAULT as identity primary key,
    name text not null,
    pokemon_num text not null
);